# branches to build
branches:
  # whitelist
  only:
  - master

# Operating system (build VM template)
image: Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x86
- x64
build:
  parallel: true
  verbosity: minimal
build_script:
- cmd: >-
    mkdir -p build/%CONFIGURATION%-%PLATFORM%

    cd build/%CONFIGURATION%-%PLATFORM%

    cmake ../.. --config %CONFIGURATION%

    cmake --build ./ --config %CONFIGURATION%
