# branches to build
branches:
  # whitelist
  only:
  - master

# Operating system (build VM template)
image: Visual Studio 2017
configuration:
- Release
- Debug
platform:
- x86
- x64
build:
  parallel: true
  verbosity: minimal
