# branches to build
branches:
  # whitelist
  only:
    - master
    - cmake

# Operating system (build VM template)
os: Visual Studio 2015

platform: x64
configuration: Release

build:
  project: C:/projects/scylla/tmp/Scylla.vcxproj      # path to Visual Studio solution or project

before_build:
    - rmdir /S /Q tinyxml
    - git clone https://github.com/lucasg/tinyxml tinyxml
    - rmdir /S /Q WTL
    - git clone https://github.com/lucasg/WindowsTemplateLibrary WTL
    - mkdir tmp
    - cd tmp
    - cmake ..