# branches to build
branches:
  # whitelist
  only:
    - master
    - cmake

# Operating system (build VM template)
os: Visual Studio 2015

platform: x64
configuration: Release

build:
  project: Scylla.vcxproj      # path to Visual Studio solution or project

before_build:
    - mkdir v140
    - cd v140
    - cmake -G "Visual Studio 14 2015 Win64" ..